Newsletter-306: translate into Chinese
PrimitivesLane/bitcoinops.github.io pull request #115
Opened 2024-06-15 15:09 UTC by hulatown

2024-06-17 01:21 UTC, freeyao requested changes
- Fixed the translation of "functional encryption"
- Term "arithmetic" needs to be decided
- Other improvement

2024-06-17 01:21 UTC, freeyao commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +本周周报宣布了即将披露的影响旧版 Bitcoin Core 的漏洞，描述了新版测试网的 BIP 草案，总结了基于功能加密的限制条款提案，检查了在比特币脚本中执行 64 位算术的更新，链接到使用 `OP_CAT` 操作码验证签名的工作量证明脚本，并探讨了 `bitcoin:` URI 的 BIP21 规范的一项更新提案。此外，还包括常规版块，用于发布新版本和候选版本，以及介绍热门比特币基础设施软件
arithmetic 用“算术”、“运算”还是“计算”？

2024-06-17 01:21 UTC, freeyao commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +  Bitcoin Core 项目的几位成员在 IRC 上[讨论了][irc disclose]披露影响旧版 Bitcoin Core 漏洞的[拟议政策][disclosure policy]。对于低严重性漏洞，将在消除（或有效缓解）该漏洞的 Bitcoin Core 版本首次发布的约两周后披露详细信息。对于大多数其他漏洞，将在受该漏洞影响的 Bitcoin Core 最后一个版本停止维护（即发
policy - 规则？ 和 mempool policy 一致？

2024-06-17 01:21 UTC, freeyao commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +- **<!--functional-encryption-covenants-->**功能加密限制条款：** Jeremy Rubin 在 Delving Bitcoin 上[发表][rubin fe post]了[论文][rubin fe paper]，介绍了如何在理论上利用[功能加密][functional encryption]为比特币添加一系列[限制条款][topic covenant
```suggestion
- **<!--functional-encryption-covenants-->**函数加密限制条款：** Jeremy Rubin 在 Delving Bitcoin 上[发表][rubin fe post]了[论文][rubin fe paper]，介绍了如何在理论上利用[函数加密][functional encryption]为比特币添加一系列[限制条款][topic covenants]，而无需修改共识。从根本上说，这需要限制条款的用户信任第三方，尽管这种信任可以分散到多方，只需要其中一方在特定时间诚实行事即可。
```

2024-06-17 01:21 UTC, freeyao commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +  本质上讲，功能加密允许创建与特定程序相对应的公钥。满足程序要求的一方将能够创建与公钥相对应的签名（无需知道相应的私钥）。
```suggestion
  本质上讲，函数加密允许创建与特定程序相对应的公钥。满足程序要求的一方将能够创建与公钥相对应的签名（无需知道相应的私钥）。
```

2024-06-17 01:21 UTC, freeyao commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +  Rubin 指出，与现有的限制条款提案相比，这种方案的优势在于所有操作（验证生成的签名除外）都在链下进行，无需在链上发布任何数据（公钥和签名除外）。这通常更加私密，而且通常可以节省空间。通过执行多次签名检查，可以在同一脚本中使用多个限制条款程序。
```suggestion
  Rubin 指出，与现有的限制条款提案相比，这种方案的优势在于所有操作（验证生成的签名除外）都在链下进行，无需在链上发布任何数据（公钥和签名除外）。这总是更加私密，而且通常可以节省空间。通过执行多次签名检查，可以在同一脚本中使用多个限制条款程序。
```

2024-06-17 01:21 UTC, freeyao commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +  除了需要可信设置外，Rubin 还描述了功能加密的另一个主要缺点，即“加密技术不够成熟，目前还无法实际使用”。
```suggestion
  除了需要可信设置外，Rubin 还描述了函数加密的另一个主要缺点，即“加密技术不够成熟，目前还无法实际使用”。
```

2024-06-17 03:38 UTC, editor-Ajian commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +本周周报宣布了即将披露的影响旧版 Bitcoin Core 的漏洞，描述了新版测试网的 BIP 草案，总结了基于功能加密的限制条款提案，检查了在比特币脚本中执行 64 位算术的更新，链接到使用 `OP_CAT` 操作码验证签名的工作量证明脚本，并探讨了 `bitcoin:` URI 的 BIP21 规范的一项更新提案。此外，还包括常规版块，用于发布新版本和候选版本，以及介绍热门比特币基础设施软件
不推荐用 “计算”。中文语境下这个词的含义太宽泛了

2024-06-17 04:34 UTC, editor-Ajian commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +本周周报宣布了即将披露的影响旧版 Bitcoin Core 的漏洞，描述了新版测试网的 BIP 草案，总结了基于功能加密的限制条款提案，检查了在比特币脚本中执行 64 位算术的更新，链接到使用 `OP_CAT` 操作码验证签名的工作量证明脚本，并探讨了 `bitcoin:` URI 的 BIP21 规范的一项更新提案。此外，还包括常规版块，用于发布新版本和候选版本，以及介绍热门比特币基础设施软件
这一段中仍用 “功能加密”，为与后文统一，应改成 “函数加密”

2024-06-17 04:34 UTC, editor-Ajian commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +  Bitcoin Core 项目的几位成员在 IRC 上[讨论了][irc disclose]披露影响旧版 Bitcoin Core 漏洞的[拟议政策][disclosure policy]。对于低严重性漏洞，将在消除（或有效缓解）该漏洞的 Bitcoin Core 版本首次发布的约两周后披露详细信息。对于大多数其他漏洞，将在受该漏洞影响的 Bitcoin Core 最后一个版本停止维护（即发
可考虑使用 “策略”。个人无倾向。

2024-06-17 04:34 UTC, editor-Ajian commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +  - *<!--new-query-parameters-->新的查询参数：* 该更新描述了三个新的键： `lightning` 用于（目前使用中的）[BOLT11][] 发票、`lno` 用于（提议中的）的闪电网络要约、以及 `sp` 用于（提议中的）静默支付。该更新还描述了未来参数的命名方式。
```suggestion
  - *<!--new-query-parameters-->新的查询参数：* 该更新描述了三个新的关键字： `lightning` 用于（目前使用中的）[BOLT11][] 发票、`lno` 用于（提议中的）的闪电网络要约、以及 `sp` 用于（提议中的）静默支付。该更新还描述了未来参数的命名方式。
```

2024-06-17 04:34 UTC, editor-Ajian commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +- [Rust Bitcoin #2644][] 在 `bitcoin_hashes` 组件中添加了 HKDF（HMAC（基于哈希的消息认证码）提取和扩展密钥派生函数），以在 Rust Bitcoin 中实现 [BIP324][]。HKDK 用于以安全、标准化的方式从密钥材料源派生加密密钥。BIP324（也称为 [v2 P2P 传输][topic v2 p2p transport]）是一种允许比
这里的原文确实分别是 “HKDF” 和 “HKDK”，但不知道后者算不算笔误

2024-06-18 03:01 UTC, hulatown commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +本周周报宣布了即将披露的影响旧版 Bitcoin Core 的漏洞，描述了新版测试网的 BIP 草案，总结了基于功能加密的限制条款提案，检查了在比特币脚本中执行 64 位算术的更新，链接到使用 `OP_CAT` 操作码验证签名的工作量证明脚本，并探讨了 `bitcoin:` URI 的 BIP21 规范的一项更新提案。此外，还包括常规版块，用于发布新版本和候选版本，以及介绍热门比特币基础设施软件
arthmetic 用“算术”应该可以，比如 [ALU](https://zh.wikipedia.org/wiki/%E7%AE%97%E8%A1%93%E9%82%8F%E8%BC%AF%E5%96%AE%E5%85%83) 翻译成“算术逻辑单元”

2024-06-18 03:03 UTC, hulatown commented on _posts/zh/newsletters/2024-06-07-newsletter.md
> +- [Rust Bitcoin #2644][] 在 `bitcoin_hashes` 组件中添加了 HKDF（HMAC（基于哈希的消息认证码）提取和扩展密钥派生函数），以在 Rust Bitcoin 中实现 [BIP324][]。HKDK 用于以安全、标准化的方式从密钥材料源派生加密密钥。BIP324（也称为 [v2 P2P 传输][topic v2 p2p transport]）是一种允许比
可能是，我去确认一下

2024-06-19 02:06 UTC, merged